version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$DB_USERNAME
      - MONGO_PASSWORD=$DB_PASSWORD
      - MONGO_HOSTNAME=$DB_HOST
      - MONGO_PORT=$DB_PORT
      - MONGO_DB=$DB_NAME
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    ports:
      - 27017:27017
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: